{% set version = "3.2.0" %}
{% set name = 'mice' %}
{% set hash = "ace986c35efb56dba9abd982e58a7aef5527b66edb376ed70ae7d287d3218566" %}

package:
  name: 'r-{{ name }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url:
    - 'https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz'
  sha256: '{{ hash }}'

build:
  skip: true  # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - make

  host:
    - r-base
    - r-mass
    - r-rcpp
    - r-lattice
    - r-nnet
    - r-rpart
    - r-survival
    - r-broom
    - r-dplyr
    - r-mitml
    - r-rlang
  run:
    - r-base
    - r-mass
    - r-rcpp
    - r-lattice
    - r-nnet
    - r-rpart
    - r-survival
    - r-broom
    - r-dplyr
    - r-mitml
    - r-rlang

test:
  commands:
    - $R -e "library('mice')"           # [not win]

about:
  home: 'http://stefvanbuuren.github.io/mice/'
  license: 'GPL-2,GPL-3'
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: |
    Multiple imputation using Fully Conditional Specification (FCS) implemented by the
    MICE algorithm as described in Van Buuren and Groothuis-Oudshoorn (2011) <doi:10.18637/jss.v045.i03>.
    Each variable has its own imputation model. Built-in imputation models are provided
    for continuous data (predictive mean matching, normal), binary data (logistic regression),
    unordered categorical data (polytomous logistic regression) and ordered categorical
    data (proportional odds). MICE can also impute continuous two-level data (normal
    model, pan, second-level variables). Passive imputation can be used to maintain
    consistency between variables. Various diagnostic plots are available to inspect
    the quality of the imputations.
  license_family: 'GPL'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - slacalle
