{% set version = "3.16.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mice
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mice_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mice/mice_{{ version }}.tar.gz
  sha256: 29f0285185a540337e9dde2357690c82d174f115be701ee2f0a7083173a44040

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-mitml                    # [build_platform != target_platform]
    - r-glmnet                   # [build_platform != target_platform]
    - r-rlang                    # [build_platform != target_platform]
    - r-dplyr                    # [build_platform != target_platform]
    - r-cpp11                    # [build_platform != target_platform]
    - r-rpart                    # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - r-tidyr                    # [build_platform != target_platform]
    - r-generics                 # [build_platform != target_platform]
    - r-lattice                  # [build_platform != target_platform]
    - r-nnet                     # [build_platform != target_platform]
    - r-broom                    # [build_platform != target_platform]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-broom                      # [build_platform != target_platform]
    - r-cpp11                      # [build_platform != target_platform]
    - r-dplyr                      # [build_platform != target_platform]
    - r-generics                   # [build_platform != target_platform]
    - r-glmnet                     # [build_platform != target_platform]
    - r-lattice                    # [build_platform != target_platform]
    - r-mitml                      # [build_platform != target_platform]
    - r-nnet                       # [build_platform != target_platform]
    - r-rlang                      # [build_platform != target_platform]
    - r-rpart                      # [build_platform != target_platform]
    - r-tidyr                      # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-broom
    - r-cpp11
    - r-dplyr
    - r-generics
    - r-glmnet
    - r-lattice
    - r-mitml
    - r-nnet
    - r-rcpp
    - r-rlang
    - r-rpart
    - r-tidyr
  run:
    - r-base
    - r-broom
    - r-cpp11
    - r-dplyr
    - r-generics
    - r-glmnet
    - r-lattice
    - r-mitml
    - r-nnet
    - r-rcpp
    - r-rlang
    - r-rpart
    - r-tidyr

test:
  commands:
    - $R -e "library('mice')"           # [not win]
    - "\"%R%\" -e \"library('mice')\""  # [win]

about:
  home: https://www.stefvanbuuren.name , https://www.stefvanbuuren.name/fimd/
  dev_url: https://github.com/stefvanbuuren/mice/
  doc_url: https://stefvanbuuren.github.io/mice/
  license: GPL-2.0-or-later
  summary: Multiple imputation using Fully Conditional Specification (FCS) implemented by the MICE algorithm as described in Van Buuren and Groothuis-Oudshoorn (2011) <doi:10.18637/jss.v045.i03>. Each variable has its own imputation model. Built-in imputation models are provided for continuous data (predictive mean matching,
    normal), binary data (logistic regression), unordered categorical data (polytomous logistic regression) and ordered categorical data (proportional odds). MICE can also impute continuous two-level data (normal model, pan, second-level variables). Passive imputation can be used to maintain consistency between variables.
    Various diagnostic plots are available to inspect the quality of the imputations.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - slacalle

# Package: mice
# Type: Package
# Version: 3.5.0
# Title: Multivariate Imputation by Chained Equations
# Date: 2019-05-13
# Authors@R: c(person("Stef", "van Buuren", role = c("aut","cre"), email = "stef.vanbuuren@tno.nl"), person("Karin", "Groothuis-Oudshoorn", role = "aut", email = "c.g.m.oudshoorn@utwente.nl"), person("Alexander", "Robitzsch", role = "ctb", email = "robitzsch@ipn.uni-kiel.de"), person("Gerko","Vink", role = "ctb", email = "g.vink@uu.nl"), person("Lisa","Doove", role = "ctb", email = "lisa.doove@ppw.kuleuven.be"), person("Shahab","Jolani", role = "ctb", email = "s.jolani@maastrichtuniversity.nl"), person("Rianne","Schouten", role = "ctb", email = "R.M.Schouten@uu.nl"), person("Philipp","Gaffert", role = "ctb", email = "philipp.gaffert@gfk.com"), person("Florian","Meinfelder", role = "ctb", email = "florian.meinfelder@uni-bamberg.de"), person("Bernie","Gray", role = "ctb", email = "bfgray3@gmail.com"))
# Maintainer: Stef van Buuren <stef.vanbuuren@tno.nl>
# Depends: methods, R (>= 2.10.0), lattice
# Imports: broom, dplyr, grDevices, graphics, MASS, mitml, nnet, parallel, Rcpp, rlang, rpart, splines, stats, survival, utils
# Suggests: AGD, CALIBERrfimpute, DPpackage, gamlss, lme4, mitools, nlme, pan, randomForest, Zelig, BSDA, knitr, rmarkdown, testthat, HSAUR3, micemd, miceadds, tidyr
# LinkingTo: Rcpp
# Description: Multiple imputation using Fully Conditional Specification (FCS) implemented by the MICE algorithm as described in Van Buuren and Groothuis-Oudshoorn (2011) <doi:10.18637/jss.v045.i03>. Each variable has its own imputation model. Built-in imputation models are provided for continuous data (predictive mean matching, normal), binary data (logistic regression), unordered categorical data (polytomous logistic regression) and ordered categorical data (proportional odds). MICE can also impute continuous two-level data (normal model, pan, second-level variables). Passive imputation can be used to maintain consistency between variables. Various diagnostic plots are available to inspect the quality of the imputations.
# Encoding: UTF-8
# License: GPL-2 | GPL-3
# LazyLoad: yes
# LazyData: yes
# URL: http://stefvanbuuren.github.io/mice/ , http://www.stefvanbuuren.name , http://www.stefvanbuuren.name/fimd/
# BugReports: https://github.com/stefvanbuuren/mice/issues
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-05-13 20:40:26 UTC; buurensv
# Author: Stef van Buuren [aut, cre], Karin Groothuis-Oudshoorn [aut], Alexander Robitzsch [ctb], Gerko Vink [ctb], Lisa Doove [ctb], Shahab Jolani [ctb], Rianne Schouten [ctb], Philipp Gaffert [ctb], Florian Meinfelder [ctb], Bernie Gray [ctb]
# Repository: CRAN
# Date/Publication: 2019-05-13 21:20:20 UTC
