# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxtarget_platformosx-64
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxtarget_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "RXSF+fEwIO9bch+K8GRabOHL/P2y4vJxffEJdKQiIKmsFT+ZenAAMUS1bxeFwRo885PwDo/tM7uQ4RKG9bM/E3iXectgh6mVr9u1ZAbX5u+5FZtKad7BZFgotrFGSpDpxdFk0ZSyYQHNYuWpLJgjZX1Tl0noUyaKpCDP3yk0RRh82s1T1Yj04x4SkNU0IUGZxUO3ZJsYl1Dgb1FpIvV3Y4Q6u8jV0q+qygYvjM+RRXLGE5o0z+ql0ZmOoTdT1EE5Q/YCLm+7pSB5ovaHgE6mPgNjogtm9blGxDsIYy1H1ZKAjFg1sbgFFn+VK0SA9QPo6ijPmyV+axC4LUDQ6JzADlpuibId0GuTeSyBEZ2gbzC/OKIByNrrB9WSlQgJCHs6gIIiH6D/yr5V31rvLz5PZcmXW1uKAXdSNSAcAK+XzxxHyng1/iDPDbnCrBwq2ZiTGPcN5Gv0EV8RvWCGi56un4WgPxveDPFGbdorMsKE+wgD9ef79X1rkvyDDphy6GmJ1d7+fMvV92zqnLS2PsyBMHtN+xbNZhSyvps3EfeKcjL8IFapzyM7LYoF7hxuHrMq7V27xcFMnycCALrhBx6WV7PiUoIgNPLQ7olDS+tAQdq/6pVAAHc2oojf1zJo7kGieM/Uz1WxT8x5cD7mGnQA5LEiicUoP2IYQ1csfjjIz20="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml