travis:
  secure:
    BINSTAR_TOKEN: M2WsAD+gtV3qGeHLIaZYtL6plQsQ8aNAqd7IYonIY4WoKU7R1ic+9gBUSId820/tXqPev5z6lIwsEA296BL/wBx/5DKWidCJPOy3ergRo3+egtClb5NHS+6BnpeD7auwe0F+xIrh5XO1Fkh2YVdTD/rKU8vWt6mQAnRPyE276u5UO+BLGpEbsGZ9tAGaxKQvWU0dei2nAKxQSjCUKdsZiLqMzn9As1Fb2R81Uz5j90wLK7WxrvrOSy42rqBP3cS/atJw2f5ygwP+qFieeDCQqD/r6Zxv7PO8lrIFwEiiPEqNY/yB1ZBcG4mz+MkG1mnUcNznyhnp1YSgYVxTwixJVZ5U0TmghDkchrk2yz8riemEhVeCAHMAzUHheuijZ3fzciXuuE0e9l5QfgPewebJl0XF042s+Byqc/NLwgjGOyauX9usEOk2IqUUHUNiUBlgeJOl53M//EHYvB9m/Zj1FgGy9FjW0N9xRn0TFMx6oFrR2aHsa52ENF2mGV7lxrTjKxfz1jmMbJ/NwJRtMd+7FFOEY6/ugROZnaZmeEzoEkSPvWiit1CrXublIZK5phD7J5t6ky96WI1ptDMJdijh77YDBtec4vLxTtvbjGQiKhgbUQPZEERzGa0t/wUZTsTeUrQgR6duhDxHMNk/2TeaOkFuLdQZA4eYCxL5VHOMEHU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
