appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: RXSF+fEwIO9bch+K8GRabOHL/P2y4vJxffEJdKQiIKmsFT+ZenAAMUS1bxeFwRo885PwDo/tM7uQ4RKG9bM/E3iXectgh6mVr9u1ZAbX5u+5FZtKad7BZFgotrFGSpDpxdFk0ZSyYQHNYuWpLJgjZX1Tl0noUyaKpCDP3yk0RRh82s1T1Yj04x4SkNU0IUGZxUO3ZJsYl1Dgb1FpIvV3Y4Q6u8jV0q+qygYvjM+RRXLGE5o0z+ql0ZmOoTdT1EE5Q/YCLm+7pSB5ovaHgE6mPgNjogtm9blGxDsIYy1H1ZKAjFg1sbgFFn+VK0SA9QPo6ijPmyV+axC4LUDQ6JzADlpuibId0GuTeSyBEZ2gbzC/OKIByNrrB9WSlQgJCHs6gIIiH6D/yr5V31rvLz5PZcmXW1uKAXdSNSAcAK+XzxxHyng1/iDPDbnCrBwq2ZiTGPcN5Gv0EV8RvWCGi56un4WgPxveDPFGbdorMsKE+wgD9ef79X1rkvyDDphy6GmJ1d7+fMvV92zqnLS2PsyBMHtN+xbNZhSyvps3EfeKcjL8IFapzyM7LYoF7hxuHrMq7V27xcFMnycCALrhBx6WV7PiUoIgNPLQ7olDS+tAQdq/6pVAAHc2oojf1zJo7kGieM/Uz1WxT8x5cD7mGnQA5LEiicUoP2IYQ1csfjjIz20=}
bot:
  automerge: true
